name: Run Unit Tests

on:
  push:
    branches:
      - main
      - task-1
      - dashboard-dev
  pull_request:
    branches:
      - main
      - task-1
      - dashboard-dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests
    - name: Run Unit Tests
      run: |
        pytest tests/ --disable-warnings
